apiVersion: batch/v1
kind: CronJob
metadata:
  name: stepcd
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: gitops
          containers:
            - name: zad2gitops 
              image: it02nowakowski/zad2_chmury_cron:latest
              command: [sh, -e, -c]
              args:
                - git clone https://github.com/JakubNowakowski98/Chmury_z2_config.git /tmp/Chmury_z2_config && kubectl apply -f /tmp/Chmury_z2_config/deployment.yml && kubectl apply -f /tmp/Chmury_z2_config/service.yml && kubectl apply -f /tmp/Chmury_z2_config/ingress.yml